services:
  - type: web
    name: launchpad-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false